--begin Hung
go 
INSERT INTO ZipCode([Province/City],District,Wards) VALUES
(N'Hồ Chí Minh', N'Quận 1', N'Phường Bến Nghé'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Bến Thành'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Cầu Kho'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Cầu Ông Lãnh'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Cô Giang'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Đa Kao'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Nguyễn Cư Trinh'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Nguyễn Thái Bình'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Phạm Ngũ Lão'),
(N'Hồ Chí Minh', N'Quận 1', N'Phường Tân Định'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường An Khánh'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường An Lợi Đông'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường An Phú'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Bình An'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Bình Khánh'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Bình Trưng Đông'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Bình Trưng Tây'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Cát Lái'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Thạnh Mỹ Lợi'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Thảo Điền'),
(N'Hồ Chí Minh', N'Quận 2', N'Phường Thủ Thiêm'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 3', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 16'),
(N'Hồ Chí Minh', N'Quận 4', N'Phường 18'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 5', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 6', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Bình Thuận'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Phú Mỹ'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Phú Thuận'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Hưng'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Kiểng'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Phong'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Phú'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Quy'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Thuận Đông'),
(N'Hồ Chí Minh', N'Quận 7', N'Phường Tân Thuận Tây'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận 8', N'Phường 16'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Hiệp Phú'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Long Bình'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Long Phước'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Long Thạnh Mỹ'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Long Trường'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Phú Hữu'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Phước Bình'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Phước Long A'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Phước Long B'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Tân Phú'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Tăng Nhơn Phú A'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Tăng Nhơn Phú B'),
(N'Hồ Chí Minh', N'Quận 9', N'Phường Trường Thạnh'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 10', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận 11', N'Phường 16'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường An Phú Đông'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Đông Hưng Thuận'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Hiệp Thành'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Tân Chánh Hiệp'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Tân Hưng Thuận'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Tân Thới Hiệp'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Tân Thới Nhất'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Thạnh Lộc'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Thạnh Xuân'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Thới An'),
(N'Hồ Chí Minh', N'Quận 12', N'Phường Trung Mỹ Tây'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận Tân Bình', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Hiệp Tân'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Hoà Thạnh'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Phú Thạnh'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Phú Thọ Hoà'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Phú Trung'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Sơn Kỳ'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Tân Quý'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Tân Sơn Nhì'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Tân Thành'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Tân Thới Hoà'),
(N'Hồ Chí Minh', N'Quận Tân Phú', N'Phường Tây Thạnh'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận Phú Nhuận', N'Phường 17'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 04'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 08'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 09'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 10'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 16'),
(N'Hồ Chí Minh', N'Quận Gò Vấp', N'Phường 17'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 01'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 02'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 03'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 05'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 06'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 07'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 11'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 12'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 13'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 14'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 15'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 17'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 19'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 21'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 22'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 24'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 25'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 26'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 27'),
(N'Hồ Chí Minh', N'Quận Bình Thạnh', N'Phường 28'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Bình Chiểu'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Bình Thọ'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Hiệp Bình Chánh'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Hiệp Bình Phước'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Linh Chiểu'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Linh Đông'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Linh Tây'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Linh Trung'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Linh Xuân'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Tam Bình'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Tam Phú'),
(N'Hồ Chí Minh', N'Quận Thủ Đức', N'Phường Trường Thọ'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường An Lạc'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường An Lạc A'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Hưng Hòa'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Hưng Hòa A'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Hưng Hòa B'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Trị Đông'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Trị Đông A'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Bình Trị Đông B'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Tân Tạo'),
(N'Hồ Chí Minh', N'Quận Bình Tân', N'Phường Tân Tạo A'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Thị Trấn Hóc Môn'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Bà Điểm'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Đông Thạnh'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Nhị Bình'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Tân Hiệp'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Tân Thới Nhì'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Tân Xuân'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Thới Tam Thôn'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Trung Chánh'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Xuân Thới Đông'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Xuân Thới Sơn'),
(N'Hồ Chí Minh', N'Huyện Hóc Môn', N'Xã Xuân Thới Thượng'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'An Nhơn Tây'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'An Phú'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Hoà Phú'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Nhuận Đức'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Phú Hòa Đông'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Phú Mỹ Hưng'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Phước Thạnh'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Phước Vĩnh An'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Tân An Hội'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Tân Phú Trung'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Tân Thạnh Đông'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Tân Thạnh Tây'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Tân Thông Hội'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Thái Mỹ'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Thị Trấn Củ Chi'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Trung An'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Trung Lập Thượng'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Xã Bình Mỹ'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Xã Phạm Văn Cội'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Xã Phước Hiệp'),
(N'Hồ Chí Minh', N'Huyện Củ Chi', N'Xã Trung Lập Hạ'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Thị Trấn Nhà Bè'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Hiệp Phước'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Long Thới'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Nhơn Đức'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Phú Xuân'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Phước Kiển'),
(N'Hồ Chí Minh', N'Huyện Nhà Bè', N'Xã Phước Lộc'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Thị Trấn Tân Túc'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã An Phú Tây'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Bình Chánh'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Bình Hưng'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Bình Lợi'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Đa Phước'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Hưng Long'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Lê Minh Xuân'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Phạm Văn Hai'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Phong Phú'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Qui Đức'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Tân Kiên'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Tân Nhựt'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Tân Quý Tây'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Vĩnh Lộc A'),
(N'Hồ Chí Minh', N'Huyện Bình Chánh', N'Xã Vĩnh Lộc B'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Thị Trấn Cần Thạnh'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã An Thới Đông'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã Bình Khánh'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã Long Hoà'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã Lý Nhơn'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã Tam Thôn Hiệp'),
(N'Hồ Chí Minh', N'Huyện Cần Giờ', N'Xã Thạnh An'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Lê Trung Tán'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Hạ Đình'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Khương Đình'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Khương Mai'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Khương Trung'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Kim Giang'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Nhân Chính'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Phương Liệt'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Thanh Xuân Bắc'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Thanh Xuân Nam'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Thanh Xuân Trung'),
(N'Hà Nội', N'Quận Thanh Xuân', N'Phường Thượng Đình'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Bưởi'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Nhật Tân'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Phú Thượng'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Quảng An'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Thuỵ Khuê'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Tứ Liên'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Xuân La'),
(N'Hà Nội', N'Quận Tây Hồ', N'Phường Yên Phụ'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Phương Canh'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Cầu Diễn'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Đại Mỗ'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Mễ Trì'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Mỹ Đình 1'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Mỹ Đình 2'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Tây Mỗ'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Trung Văn'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Phường Xuân Phương'),
(N'Hà Nội', N'Quận Nam Từ Liêm', N'Xã Phú Đô'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Bồ Đề'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Cự Khối'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Đức Giang'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Gia Thuỵ'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Giang Biên'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Long Biên'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Ngọc Lâm'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Ngọc Thuỵ'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Phúc Đồng'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Phúc Lợi'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Sài Đồng'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Thạch Bàn'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Thượng Thanh'),
(N'Hà Nội', N'Quận Long Biên', N'Phường Việt Hưng'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Đại Kim'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Định Công'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Giáp Bát'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Hoàng Liệt'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Hoàng Văn Thụ'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Lĩnh Nam'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Mai Động'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Tân Mai'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Thanh Trì'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Thịnh Liệt'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Trần Phú'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Tương Mai'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Vĩnh Hưng'),
(N'Hà Nội', N'Quận Hoàng Mai', N'Phường Yên Sở'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Chiếu'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Chương Dương Độ'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Cửa Đông'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Cửa Nam'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Đồng Xuân'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Bạc'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Bài'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Bồ'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Bông'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Buồm'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Đào'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Gai'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Mã'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Hàng Trống'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Lý Thái Tổ'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Phan Chu Trinh'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Phúc Tân'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Trần Hưng Đạo'),
(N'Hà Nội', N'Quận Hoàn Kiếm', N'Phường Tràng Tiền'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Bạch Đằng'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Bách Khoa'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Bạch Mai'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Bùi Thị Xuân'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Cầu Dền'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Đống Mác'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Đồng Nhân'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Đồng Tâm'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Lê Đại Hành'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Minh Khai'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Ngô Thì Nhậm'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Nguyễn Du'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Phạm Đình Hổ'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Phố Huế'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Quỳnh Lôi'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Quỳnh Mai'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Thanh Lương'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Thanh Nhàn'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Trương Định'),
(N'Hà Nội', N'Quận Hai Bà Trưng', N'Phường Vĩnh Tuy'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Hà Cầu'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường La Khê'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Mỗ Lao'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Mộ Lao'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Nguyễn Trãi'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Phú La'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Phúc La'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Quang Trung'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Vạn Phúc'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Văn Quán'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Yên Nghĩa'),
(N'Hà Nội', N'Quận Hà Đông', N'Phường Yết Kiêu'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Biên Giang'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Đồng Mai'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Dương Nội'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Kiến Hưng'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Phú Lãm'),
(N'Hà Nội', N'Quận Hà Đông', N'Xã Phú Lương'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Cát Linh'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Hàng Bột'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Khâm Thiên'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Khương Thượng'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Kim Liên'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Láng Hạ'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Láng Thượng'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Nam Đồng'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Ngã Tư Sở'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường ô Chợ Dừa'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Phương Liên'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Phương Mai'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Quang Trung'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Quốc Tử Giám'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Thịnh Quang'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Thổ Quan'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Trung Liệt'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Trung Phụng'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Trung Tự'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Văn Chương'),
(N'Hà Nội', N'Quận Đống Đa', N'Phường Văn Miếu'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Dịch Vọng'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Dịch Vọng Hậu'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Mai Dịch'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Nghĩa Đô'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Nghĩa Tân'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Quan Hoa'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Trung Hoà'),
(N'Hà Nội', N'Quận Cầu Giấy', N'Phường Yên Hoà'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Cổ Nhuế'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Cổ Nhuế 1'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Cổ Nhuế 2'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Đông Ngạc'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Đức Thắng'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Liên Mạc'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Minh Khai'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Phú Diễn'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Phúc Diễn'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Tây Tựu'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Thượng Cát'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Thụy Phương'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Xuân Đỉnh'),
(N'Hà Nội', N'Quận Bắc Từ Liêm', N'Phường Xuân Tảo'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Nguyễn Trung Trực'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Cống Vị'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Điện Biên'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Đội Cấn'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Giảng Võ'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Kim Mã'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Liễu Giai'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Ngọc Hà'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Ngọc Khánh'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Phúc Xá'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Quán Thánh'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Thành Công'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Trúc Bạch'),
(N'Hà Nội', N'Quận Ba Đình', N'Phường Vĩnh Phúc'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Thị trấn Long Điền'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Thị trấn Long Hải'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Xã An Ngãi'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Xã An Nhứt'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Xã Phước Hưng'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Xã Phước Tỉnh'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Long Điền', N'Xã Tam Phước'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Thị trấn Ngãi Giao'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Bàu Chinh'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Bình Ba'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Bình Giã'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Bình Trung'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Cù Bị'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Láng Lớn'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Quảng Thành'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Suối Nghệ'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Châu Đức', N'Xã Suối Rao'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Thị trấn Phước Bửu'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Bàu Lâm'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Bình Châu'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Hòa Bình'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Hòa Hiệp'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Hòa Hội'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Hòa Hưng'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Phước Tân'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Phước Thuận'),
(N'Bà Rịa - Vũng Tàu', N'Huyện Xuyên Mộc', N'Xã Tân Lâm'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Thị trấn Dầu Tiếng'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã An Lập'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Định An'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Định Hiệp'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Định Thành'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Long Hoà'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Long Tân'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Minh Hoà'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Minh Tân'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Minh Thạnh'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Thanh An'),
(N'Bình Dương', N'Huyện Dầu Tiếng', N'Xã Thanh Tuyền'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Thị trấn Phước Vĩnh'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã An Bình'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã An Linh'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã An Long'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã An Thái'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Phước Hoà'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Phước Sang'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Tam Lập'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Tân Hiệp'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Tân Long'),
(N'Bình Dương', N'Huyện Phú Giáo', N'Xã Vĩnh Hoà'),
(N'Đồng Nai', N'TP. Biên Hòa', N'An Hòa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Long Hưng'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phước Tân'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường An Bình'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Bình Đa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Bửu Hòa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Bửu Long'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Hố Nai'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Hòa Bình'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Long Bình'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Long Bình Tân'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Quang Vinh'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Quyết Thắng'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tam Hiệp'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tam Hòa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Biên'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Hiệp'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Hòa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Mai'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Phong'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Tiến'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Tân Vạn'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Thanh Bình'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Thống Nhất'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Trảng Dài'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Phường Trung Dũng'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Tam Phước'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Xã Hiệp Hòa'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Xã Hóa An'),
(N'Đồng Nai', N'TP. Biên Hòa', N'Xã Tân Hạnh'),
(N'Đồng Nai', N'Huyện Long Thành', N'Thị trấn Long Thành'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Cẩm Đường'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Lộc An'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Bình Sơn'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Long Đức'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Long Phước'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Tam An'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Tân Hiệp'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Suối Trầu'),
(N'Đồng Nai', N'Huyện Long Thành', N'Xã Phước Bình'),
(N'Đồng Nai', N'Huyện Thống Nhất', N'Quảng Tiến'),
(N'Đồng Nai', N'Huyện Thống Nhất', N'Xã Gia Kiệm'),
(N'Đồng Nai', N'Huyện Thống Nhất', N'Xã Hưng Lộc'),
(N'Đồng Nai', N'Huyện Thống Nhất', N'Xã Xuân Thạnh'),
(N'Đồng Nai', N'Huyện Thống Nhất', N'Xã Quang Trung'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Đại Phước'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Hiệp Phước'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Long Tân'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Long Thọ'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phú Đông'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phú Hội'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phú Hữu'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phú Thạnh'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phước An'),
(N'Đồng Nai', N'Huyện Nhơn Trạch', N'Xã Phước Khánh'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Hòa Phát'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Hoà An'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Hoà Phát'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Hoà Thọ Đông'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Hoà Thọ Tây'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Hoà Xuân'),
(N'Đà Nẵng', N'Quận Cẩm Lệ', N'Phường Khuê Trung'),
(N'Đà Nẵng', N'Quận Liên Chiểu', N'Phường Hoà Hiệp Bắc'),
(N'Đà Nẵng', N'Quận Liên Chiểu', N'Phường Hoà Hiệp Nam'),
(N'Đà Nẵng', N'Quận Liên Chiểu', N'Phường Hoà Khánh Bắc'),
(N'Đà Nẵng', N'Quận Liên Chiểu', N'Phường Hoà Khánh Nam'),
(N'Đà Nẵng', N'Quận Liên Chiểu', N'Phường Hoà Minh'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Bình Hiên'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Bình Thuận'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hải Châu I'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hải Châu II'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hoà Cường Bắc'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hoà Cường Nam'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hoà Thuận Đông'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Hoà Thuận Tây'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Nam Dương'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Phước Ninh'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Thạch Thang'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Thanh Bình'),
(N'Đà Nẵng', N'Quận Hải Châu', N'Phường Thuận Phước'),
(N'Khánh Hòa', N'TP. Cam Ranh', N'Phường Cam Lợi'),
(N'Khánh Hòa', N'TP. Cam Ranh', N'Phường Cam Thuận'),
(N'Khánh Hòa', N'TP. Cam Ranh', N'Xã Cam Bình'),
(N'Khánh Hòa', N'TP. Cam Ranh', N'Xã Cam Thịnh Đông'),
(N'Khánh Hòa', N'TP. Cam Ranh', N'Phường Ba Ngòi'),
(N'Kiên Giang', N'Huyện Châu Thành', N'Thị trấn Minh Lương'),
(N'Kiên Giang', N'Huyện Châu Thành', N'Xã Minh Hòa'),
(N'Kiên Giang', N'Huyện Châu Thành', N'Xã Thạnh Lộc'),
(N'Kiên Giang', N'Huyện Châu Thành', N'Xã Vĩnh Hoà Phú'),
(N'Kiên Giang', N'Huyện Châu Thành', N'Xã Mong Thọ A'),
(N'An Giang', N'TP. Long Xuyên', N'Phường Bình Đức'),
(N'An Giang', N'TP. Long Xuyên', N'Phường Bình Khánh'),
(N'An Giang', N'TP. Long Xuyên', N'Phường Đông Xuyên'),
(N'An Giang', N'TP. Long Xuyên', N'Phường Mỹ Hòa'),
(N'An Giang', N'TP. Long Xuyên', N'Xã Mỹ Khánh'),
(N'Bình Phước', N'Thị xã Bình Long', N'Thị trấn An Lộc'),
(N'Bình Phước', N'Thị xã Bình Long', N'Xã An Khương'),
(N'Bình Phước', N'Thị xã Bình Long', N'Xã An Phú'),
(N'Bình Phước', N'Thị xã Bình Long', N'Xã Thanh Bình'),
(N'Bình Phước', N'Thị xã Bình Long', N'Xã Thanh Phú'),
(N'Cần Thơ', N'Quận Ninh Kiều', N'Phường An Cư'),
(N'Cần Thơ', N'Quận Ninh Kiều', N'Phường An Hội'),
(N'Cần Thơ', N'Quận Ninh Kiều', N'Phường An Khánh'),
(N'Cần Thơ', N'Quận Ninh Kiều', N'Phường An Lạc'),
(N'Cần Thơ', N'Quận Ninh Kiều', N'Phường Xuân Khánh'),
(N'Đồng Tháp', N'TP. Cao Lãnh', N'Phường Mỹ Phú'),
(N'Đồng Tháp', N'TP. Cao Lãnh', N'Xã Hòa An'),
(N'Đồng Tháp', N'TP. Cao Lãnh', N'Xã Mỹ Ngãi'),
(N'Đồng Tháp', N'TP. Cao Lãnh', N'Xã Mỹ Tân'),
(N'Đồng Tháp', N'TP. Cao Lãnh', N'Xã Tân Thuận Đông'),
(N'Thanh Hóa', N'TP. Sầm Sơn', N'Phường Bắc Sơn'),
(N'Thanh Hóa', N'TP. Sầm Sơn', N'Phường Trung Sơn'),
(N'Thanh Hóa', N'TP. Sầm Sơn', N'Quảng Châu'),
(N'Thanh Hóa', N'TP. Sầm Sơn', N'Xã Quảng Minh'),
(N'Thanh Hóa', N'TP. Sầm Sơn', N'Xã Quảng Vinh'),
(N'Thái Bình', N'TP. Thái Bình', N'Phường Bồ Xuyên'),
(N'Thái Bình', N'TP. Thái Bình', N'Phường Đề Thám'),
(N'Thái Bình', N'TP. Thái Bình', N'Phường Hoàng Diệu'),
(N'Thái Bình', N'TP. Thái Bình', N'Xã Đông Hòa'),
(N'Thái Bình', N'TP. Thái Bình', N'Xã Vũ Lạc'),
(N'Kon Tum', N'TP. Kon Tum', N'Phường Duy Tân'),
(N'Kon Tum', N'TP. Kon Tum', N'Phường Lê Lợi'),
(N'Kon Tum', N'TP. Kon Tum', N'Phường Ngô Mây'),
(N'Kon Tum', N'TP. Kon Tum', N'Phường Quyết Thắng'),
(N'Kon Tum', N'TP. Kon Tum', N'Phường Trường Chinh'),
(N'Lai Châu', N'TP. Lai Châu', N'Đông Phong'),
(N'Lai Châu', N'TP. Lai Châu', N'Phường Đoàn Kết'),
(N'Lai Châu', N'TP. Lai Châu', N'Phường Tân Phong'),
(N'Lai Châu', N'TP. Lai Châu', N'Xã Nậm Loong'),
(N'Lai Châu', N'TP. Lai Châu', N'Xã San Thàng'),
(N'Lâm Đồng', N'TP. Bảo Lộc', N'Phường Lộc Phát'),
(N'Lâm Đồng', N'TP. Bảo Lộc', N'Phường Lộc Sơn'),
(N'Lâm Đồng', N'TP. Bảo Lộc', N'Phường Lộc Tiến'),
(N'Lâm Đồng', N'TP. Bảo Lộc', N'Xã Đại Lào'),
(N'Lâm Đồng', N'TP. Bảo Lộc', N'Xã Lộc Thanh'),
(N'Bắc Giang', N'TP. Bắc Giang', N'Phường Hoàng Văn Thụ'),
(N'Bắc Giang', N'TP. Bắc Giang', N'Phường Lê Lợi'),
(N'Bắc Giang', N'TP. Bắc Giang', N'Phường Mỹ Độ'),
(N'Bắc Giang', N'TP. Bắc Giang', N'Phường Thọ Xương'),
(N'Bắc Giang', N'TP. Bắc Giang', N'Xã Đồng Sơn'),
(N'Lạng Sơn', N'Huyện Bắc Sơn', N'Thị trấn Bắc Sơn'),
(N'Lạng Sơn', N'Huyện Bắc Sơn', N'Xã Chiến Thắng'),
(N'Lạng Sơn', N'Huyện Bắc Sơn', N'Xã Chiêu Vũ'),
(N'Lạng Sơn', N'Huyện Bắc Sơn', N'Xã Quỳnh Sơn'),
(N'Lạng Sơn', N'Huyện Bắc Sơn', N'Xã Tân Lập'),
(N'Bắc Kạn', N'TP. Bắc Kạn', N'Phường Đức Xuân'),
(N'Bắc Kạn', N'TP. Bắc Kạn', N'Phường Phùng Chí Kiên'),
(N'Bắc Kạn', N'TP. Bắc Kạn', N'Xã Dương Quang'),
(N'Bắc Kạn', N'TP. Bắc Kạn', N'Xã Nông Thượng'),
(N'Bắc Kạn', N'TP. Bắc Kạn', N'Xã Xuất Hoá'),
(N'Lào Cai', N'TP. Lào Cai', N'Phường Bắc Cường'),
(N'Lào Cai', N'TP. Lào Cai', N'Phường Bắc Lệnh'),
(N'Lào Cai', N'TP. Lào Cai', N'Phường Bình Minh'),
(N'Lào Cai', N'TP. Lào Cai', N'Xã Cam Đường'),
(N'Lào Cai', N'TP. Lào Cai', N'Xã Hợp Thành'),
(N'Bạc Liêu', N'TP. Bạc Liêu', N'Xã Hiệp Thành'),
(N'Bạc Liêu', N'TP. Bạc Liêu', N'Xã Vĩnh Trạch'),
(N'Bạc Liêu', N'TP. Bạc Liêu', N'Xã Vĩnh Trạch Đông'),
(N'Long An', N'TP. Tân An', N'Phường Khánh Hậu'),
(N'Long An', N'TP. Tân An', N'Phường Tân Khánh'),
(N'Long An', N'TP. Tân An', N'Xã An Vĩnh Ngãi'),
(N'Long An', N'TP. Tân An', N'Xã Bình Tâm'),
(N'Long An', N'TP. Tân An', N'Xã Nhơn Thạnh Trung'),
(N'Bắc Ninh', N'TP. Bắc Ninh', N'Phường Đại Phúc'),
(N'Bắc Ninh', N'TP. Bắc Ninh', N'Phường Suối Hoa'),
(N'Bắc Ninh', N'TP. Bắc Ninh', N'Phường Tiền An'),
(N'Bắc Ninh', N'TP. Bắc Ninh', N'Xã Hòa Long'),
(N'Bắc Ninh', N'TP. Bắc Ninh', N'Xã Nam Sơn'),
(N'Nam Định', N'TP. Nam Định', N'Phường Bà Triệu'),
(N'Bến Tre', N'TP. Bến Tre', N'Phường Phú Khương'),
(N'Nghệ An', N'Huyện Anh Sơn', N'Thị trấn Anh Sơn'),
(N'Bình Định', N'TP. Quy Nhơn', N'Phường Bùi Thị Xuân'),
(N'Ninh Bình', N'TP. Ninh Bình', N'Phường Đông Thành'),
(N'Ninh Thuận', N'TP. Phan Rang-Tháp Chàm', N'Phường Bảo An'),
(N'Phú Thọ', N'Huyện Cẩm Khê', N'Xã Tam Sơn'),
(N'Bình Thuận', N'TP. Phan Thiết', N'Phường Bình Hưng'),
(N'Phú Yên', N'Huyện Đồng Xuân', N'Xã Xuân Lãnh'),
(N'Cà Mau', N'TP. Cà Mau', N'Tân Xuyên'),
(N'Quảng Bình', N'TP. Đồng Hới', N'Phường Bắc Lý'),
(N'Quảng Nam', N'TP. Tam Kỳ', N'Phường An Mỹ'),
(N'Cao Bằng', N'Huyện Bảo Lâm', N'Xã Đức Hạnh'),
(N'Quảng Ngãi', N'TP. Quảng Ngãi', N'Phường Nghĩa Chánh'),
(N'Đắk Lắk', N'TP. Buôn Ma Thuột', N'Phường Khánh Xuân'),
(N'Quảng Ninh', N'TP. Hạ Long', N'Phường Bạch Đằng'),
(N'Đắk Nông', N'Huyện Đăk Mil', N'Thị trấn Đắk Mil'),
(N'Quảng Trị', N'Huyện Cam Lộ', N'Thị trấn Cam Lộ'),
(N'Điện Biên', N'TP. Điện Biên Phủ', N'Phường Mường Thanh'),
(N'Sóc Trăng', N'Huyện Châu Thành', N'Thị trấn Châu Thành'),
(N'Sơn La', N'TP. Sơn La', N'Phường Chiềng An'),
(N'Tây Ninh', N'TP. Tây Ninh', N'Phường Hiệp Ninh'),
(N'Gia Lai', N'Thị xã An Khê', N'Phường Tây Sơn'),
(N'Hà Giang', N'TP. Hà Giang', N'Phường Minh Khai'),
(N'Thái Nguyên', N'Huyện Đại Từ', N'Thị trấn Đại Từ'),
(N'Hà Nam', N'Huyện Bình Lục', N'Thị trấn Bình Mỹ'),
(N'Hà Tĩnh', N'TP. Hà Tĩnh', N'Phường Bắc Hà'),
(N'Thừa Thiên Huế', N'TP. Huế', N'Phường An Đông'),
(N'Hải Dương', N'TP. Hải Dương', N'Phường Phạm Ngũ Lão'),
(N'Tiền Giang', N'Huyện Cái Bè', N'Thị trấn Cái Bè'),
(N'Hải Phòng', N'Huyện An Dương', N'Thị trấn An Dương'),
(N'Trà Vinh', N'TP. Trà Vinh', N'Xã Long Đức'),
(N'Hậu Giang', N'Huyện Châu Thành', N'Xã Đông Thạnh'),
(N'Tuyên Quang', N'TP. Tuyên Quang', N'Phường Đội Cấn'),
(N'Hòa Bình', N'TP. Hòa Bình', N'Phường Đồng Tiến'),
(N'Vĩnh Long', N'TP. Vĩnh Long', N'Xã Tân Hòa'),
(N'Hưng Yên', N'TP. Hưng Yên', N'Phường An Tảo'),
(N'Vĩnh Phúc', N'TP. Vĩnh Yên', N'Phường Tích Sơn'),
(N'Yên Bái', N'Huyện Lục Yên', N'Thị trấn Yên Thế'),
(N'Yên Bái', N'Huyện Lục Yên', N'Xã Mường Lai'),
(N'Yên Bái', N'Huyện Lục Yên', N'Xã An Lạc'),
(N'Yên Bái', N'TP. Yên Bái', N'Phường Đồng Tâm'),
(N'Yên Bái', N'TP. Yên Bái', N'Phường Minh Tân'),
(N'Yên Bái', N'TP. Yên Bái', N'Phường Nguyễn Thái Học'),
(N'Yên Bái', N'TP. Yên Bái', N'Xã Phúc Lộc')
--end Hung